### ISSUE TITLE
malisiscore 0.13.0 crashing on server

### ISSUE THREAD

**Issue by sircrimer** [Ordinastie/MalisisCore#59] opened 2015-11-11 13:32 UTC
[14:33:17] [main/DEBUG] [FML/]: Validating minecraft
[14:33:17] [main/DEBUG] [FML/]: Minecraft validated, launching...
[14:33:17] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:33:17] [main/DEBUG] [FML/]: Injecting coremod LoadingPlugin {cofh.asm.LoadingPlugin} class transformers
[14:33:17] [main/TRACE] [FML/]: Registering transformer cofh.asm.CoFHClassTransformer
[14:33:17] [main/DEBUG] [FML/]: Injection complete
[14:33:17] [main/DEBUG] [FML/]: Running coremod plugin for LoadingPlugin {cofh.asm.LoadingPlugin}
[14:33:17] [main/DEBUG] [FML/]: Running coremod plugin LoadingPlugin
[14:33:17] [main/DEBUG] [FML/]: Coremod plugin class LoadingPlugin run successfully
[14:33:17] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:33:17] [main/DEBUG] [FML/]: Injecting coremod MalisisCorePlugin {net.malisis.core.asm.MalisisCorePlugin} class transformers
[14:33:18] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_65]
    at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_65]
    at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_65]
    at javax.swing.JFrame.<init>(JFrame.java:233) ~[?:1.8.0_65]
    at net.malisis.javacompat.JavaCompatibility.<init>(JavaCompatibility.java:47) ~[JavaCompatibility.class:1.7.10-0.13.0]
    at net.malisis.javacompat.JavaCompatibility.checkVersion(JavaCompatibility.java:205) ~[JavaCompatibility.class:1.7.10-0.13.0]
    at net.malisis.core.asm.MalisisCorePlugin.getASMTransformerClass(MalisisCorePlugin.java:41) ~[malisiscore-1.7.10-0.13.0.jar:1.7.10-0.13.0]
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:105) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:971)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:33:18] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 6 more

**Comment by kreezxil** [comment] 2015-11-12 01:34
I got the same thing:
[20:28:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[20:28:19] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[20:28:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[20:28:20] [main/INFO] [FML]: Forge Mod Loader version 11.14.3.1562 for Minecraft 1.8 loading
[20:28:20] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Linux:amd64:2.6.32-042stab093.5, installed at /usr/lib/jvm/java-8-oracle/jre
[20:28:21] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.8-1.8.3.49-server.jar
[20:28:21] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod com.hitchh1k3rsguide.makersmark.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from moving-world-1.8-1.8.1.jar
[20:28:21] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/WARN] [FML]: The coremod thaumcraft.loader.ThaumcraftLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:28:21] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[20:28:21] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:28:21] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.5 Source=file:/root/development/extreme/mods/forgeessentials-1.8-1.8.3.49-server.jar Env=SERVER
[20:28:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:28:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:28:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:28:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/hibernate-commons-annotations-4.0.5.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/mysql-connector-java-5.1.22.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/dom4j-1.6.1.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/antlr-2.7.7.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/jboss-logging-annotations-1.2.0.Beta1.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/slf4j-api-1.7.5.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/hibernate-core-4.3.7.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/hibernate-entitymanager-4.3.7.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/jandex-1.1.0.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/pircbotx-2.0.1.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/jboss-transaction-api_1.2_spec-1.0.0.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/hibernate-jpa-2.1-api-1.0.0.Final.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/jboss-logging-3.1.3.GA.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/javassist-3.18.1-GA.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/xml-apis-1.0.b2.jar to classpath
[20:28:23] [main/INFO] [ForgeEssentials]: Added library /root/development/extreme/ForgeEssentials/lib/h2-1.3.175.jar to classpath
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[20:28:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:28:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:24] [main/INFO] [STDOUT]: [com.creativemd.itemphysic.ItemTransformer:transform:71]: [ItemPhysic] Running in obfuscated mode!
[20:28:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:28:24] [main/ERROR] [LaunchWrapper]: Unable to launch
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_66]
        at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_66]
        at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_66]
        at javax.swing.JFrame.<init>(JFrame.java:233) ~[?:1.8.0_66]
        at net.malisis.javacompat.JavaCompatibility.<init>(JavaCompatibility.java:47) ~[JavaCompatibility.class:1.8-1.0.0]
        at net.malisis.javacompat.JavaCompatibility.checkVersion(JavaCompatibility.java:205) ~[JavaCompatibility.class:1.8-1.0.0]
        at net.malisis.core.asm.MalisisCorePlugin.getASMTransformerClass(MalisisCorePlugin.java:41) ~[malisis-core-1.8-1.0.0.jar:1.8-1.0.0]
        at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:117) ~[experimental.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [experimental.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [experimental.jar:?]
A problem occurred running the Server launcher.[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:497)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:28:24] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more

**Comment by Ordinastie** [comment] 2015-11-12 02:34
Fixed in latest MalisisCore version (1.7.10-0.13.1 and 1.8-1.0.1)

**Closed as completed by Ordinastie** 2015-11-12 02:34 UTC
