### ISSUE TITLE
Door Factory Error

### ISSUE THREAD

**Issue by kwpugh** [Ordinastie/MalisisCore#64] opened 2016-02-21 19:51 UTC
Forge: forge-1.7.10-10.13.4.1614-1.7.10
Malisis:   malisisdoors-1.7.10-1.13.0 & malisiscore-1.7.10-0.14.2

Error: "A problem occurred while constructing NullPointerException: null"

Error occurs when the player attempts to right-click a placed Door Factory (both existing and newly placed).

**Comment by Ordinastie** [comment] 2016-02-21 23:12
Please use latest version of MalisisDoors. 
Also, please provide full log.

**Comment by psychofad** [comment] 2016-02-22 20:44
Using the latest version of MalisisDoors this error still occurs.  Rolling Malisiscore back to 14.1 resolves the issue.  There is no error created in the log file at all, the Error that kwpugh referred to only shows up in chat in-game and the GUI refuses to open on the door factory.

**Comment by Ordinastie** [comment] 2016-02-22 20:56
That message says nothing, that's why I need the full log.
Also, I just updated MalisisCore to 0.14.3, maybe that'll help.

**Comment by psychofad** [comment] 2016-02-22 20:58
Well, it appears the issue is fixed in the latest Malisiscore v14.3,  must have been an issue with optifine since that is the only thing i see you changed in the commits.

**Comment by Ordinastie** [comment] 2016-02-22 21:10
Good.
For future reference, you have a latest.log  file in the logs folder, and that is required for a modder to know what doesn't work.

**Closed as completed by Ordinastie** 2016-02-22 21:10 UTC
